### PR TITLE
Fixing build and updating osxtools

### PR DESCRIPTION
**Pull request by artynet**
please consider my PR for updating your system. It works on Debian Buster as well...

* Fixes build with Debian Stretch
* osxtools are updated to release g542acc2

### CODE REVIEW

**Comment by lafin** [comment]
@artynet 👍

**Comment by artynet** [comment]
Thank you @iafin for  accepting my PR ! you can switch to Buster anytime you want...the Dockerfile is fully compatible ;)

**Comment by inolen** [comment]
HI @lafin, 

Has this PR actually been tested? Diffing it with my own patch from #40 and it's missing some fairly critical steps:

```ln -s /usr /usr/x86_64-linux-gnu/x86_64-linux-gnu``` is absolutely required after updating to Stretch.

Checking that $bin exists is also critical in the event that `/usr/bin/$triple-*` doesn't exist or else the build will fail.

I've tested the patch from https://github.com/multiarch/crossbuild/pull/40#issuecomment-570222064 on x86_64-apple-darwin, x86_64-w64-mingw32 and default x86_64-linux-gnu and I'm fairly sure what's posted here will not function for these.

**Comment by artynet** [comment]
hello @inolen, does this work for you ?

```patch
 diff --git a/assets/crossbuild b/assets/crossbuild
 index 098b762..8e1ee2d 100755
 --- a/assets/crossbuild
 +++ b/assets/crossbuild
 @@ -40,7 +40,7 @@ if [ -z ${LD_LIBRARY_PATH_ORIGIN+x} ]; then export LD_LIBRARY_PATH_ORIGIN=${LD_L
  if [ -n "${CROSS_TRIPLE}" ]; then
      export CROSS_ROOT="/usr/${CROSS_TRIPLE}"
      export PATH="${CROSS_ROOT}/bin:${PATH_ORIGIN}"
 -    export LD_LIBRARY_PATH="/usr/x86_64-linux-gnu/${CROSS_TRIPLE}/lib:${LD_LIBRARY_PATH_ORIGIN}"
 +    export LD_LIBRARY_PATH="/usr/x86_64-linux-gnu/${CROSS_TRIPLE}/lib:/usr/osxcross/lib:${LD_LIBRARY_PATH_ORIGIN}"
  fi
  
  # try to exec direct binary instead on relying on the $PATH
```
concerning the `LD_LIBRARY_PATH` ? if you look at the travis build, the hello-world examples are successfully built...

**Pull request merged**
